### PR TITLE
Multiple instances

### PR DESCRIPTION
**Pull request by chrissrogers**
- Allows a the recurly singleton to spawn new instances without colliding with each others messages
- Allows an instance to be safely destroyed, removing its listeners and unbinding it from the DOM.

### CODE REVIEW

**Comment by jayseeg** [comment]
+1

**Comment by irnnr** [comment]
So how would one use this now?

**Comment by chrissrogers** [comment]
The module's export is still a singleton `recurly`, but the internals allow for you to call the `recurly.configure` method many times with different targets for the hosted fields, and now the library will reinstantiate using the new targets.

**Comment by irnnr** [comment]
Ok, I think that much was clear. But how are the different targets defined?  
Could the documentation be updated on that topic?

**Comment by chrissrogers** [comment]
@irnnr simply call `recurly.configure` with different values for the field selectors.

```js
recurly.configure({
  // ...
  fields: {
    number: { selector: '#recurly-number-1' }
  }
});

recurly.configure({
  // ...
  fields: {
    number: { selector: '#recurly-number-2' }
  }
});
```

**Pull request merged**
