### PR TITLE
fix: switch to using window over global

### PR DESCRIPTION
**Pull request by thisislawatts**
As mentioned in #455 it would be good to remove use of eval. To facilitate that change we need to remove use of `global` within the library and instead use `window`

### CODE REVIEW

**Comment by thisislawatts** [comment]
🕵️‍♀️

**Comment by chrissrogers** [comment]
Thanks for this! Yeah that's exactly right on the sauce front. I'll just run the tests locally to confirm.

**Comment by thisislawatts** [comment]
Thanks @chrissrogers let me know if there's anything else I can look into on this.

**Comment by chrissrogers** [comment]
This is looking good. Thanks for the contrib!

**Comment by thisislawatts** [comment]
@chrissrogers No problem, thanks for helping get this turned around so quickly. 🙇

**Pull request merged**
