### PR TITLE
Update config type with requiredShippingContactFields

### PR DESCRIPTION
**Pull request by BARK-RMILLER**
Recurly.js now accepts the `requiredShippingContactFields` option: https://recurly.com/developers/reference/recurly-js/#apple-pay but attempting to set this option in a typescript setup will result in a TS error.

### CODE REVIEW

**Review by chrissrogers — APPROVED** [review]

**Comment by chrissrogers** [comment]
Thank you for the contrib!

**Comment by chrissrogers** [comment]
Looks like there's a simple linter issue and an array format error coming up in the [spec run](https://app.travis-ci.com/github/recurly/recurly-js/jobs/599560638#L324)

**Comment by BARK-RMILLER** [comment]
@chrissrogers: It seems like my PR passed the lint check but its failing some cross-browser tests. Is there anything I can do on this pr to fix this?

I'm gonna be offline for a bit so feel free to take this across the finish line if its easy.

Thanks!

**Comment by chrissrogers** [comment]
Merging this after validating tests locally.

**Pull request merged**
